spring.application.name: RaftServer
logging:
    level:
        root: error
        org.example.raftserver.raft: info
    pattern:
        console: "%d{HH:mm:ss} - %clr(%-5level) [%thread] %logger{36} - %msg%n"