spring.application.name: RaftServer
raft:
    node-id: node2
    port: 8182
    client-port: 18082
    data-path: /tmp/raft/node1
    election-timeout-min: 1500
    election-timeout-max: 3000
    heartbeat-timeout: 1000
    heartbeat-interval: 100

    peers:
        - node-id: node1
          ip: 127.0.0.1
          port: 8181
        - node-id: node2
          ip: 127.0.0.1
          port: 8182
        - node-id: node3
          ip: 127.0.0.1
          port: 8183